version: "3"
services:
  mysql:
    container_name: mysql-1
    build: ./docker/mysql
    image: mysql-1:5.6
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
    - ./mysql/mysql_data:/var/lib/mysql
    - ./mysql/mysql_db.cnf:/etc/mysql/conf.d/mysql_db.cnf
    expose:
    - "3306"
  java:
    container_name: java-1
    build: .
    image: java-1:test
    depends_on:
      - mysql
    links:
      - mysql
    environment:
       MYSQL_IP: mysql
       MYSQL_PORT: 3306
       USERNAME: root
       MYSQL_ROOT_PASSWORD: 123456
       DBNAME: dump
       COUNTRYID: 2
       CUSTOMERID: 130