version: "3"
services:
  mysql-1:
    container_name: mysql-3
    build: ./docker/mysql
    image: javatest3/mysql:1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  java-1:
    container_name: java-3
    build: ./docker/java
    image: javatest3/java:1.0
    depends_on:
      - mysql-1
    links:
      - mysql-1
    environment:
      MYSQL_IP: mysql-1
      MYSQL_PORT: 3306
      countryId: 2
      customerId: 130